//Ajax Call
export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR"

//Dashboard
export const LOAD_DASHBOARD_DEFAULT = "LOAD_DASHBOARD_DEFAULT";
export const CHANGE_DASHBOARD_CATEGORY = "CHANGE_DASHBOARD_CATEGORY";

//Authors
export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";